# matrix:
#   include:
#     - os: linux
#       dist: xenial
#       sudo: required
#     - os: osx
#       osx_image: xcode8.2
#   allow_failures:
#     - os: osx

os: linux
dist: xenial
sudo: required

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # - "3.5-dev" # 3.5 development branch
  # - "3.6-dev" # 3.6 development branch
  # - "nightly" # currently points to 3.7-dev

# http://stackoverflow.com/questions/30588634/install-numpy-1-8-in-travis-ci
before_install:
  - ./.travis/before_install.sh

# command to install dependencies
install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda install --yes --file requirements.txt
  - conda list
  - pip install -r futures_requirements.txt
  - pip install setuptools
  - pip list

# command to run tests
script: pytest