language: python

sudo: false

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
#    As of 01/22/2017, "Python builds are not available on the OSX environment."
#    https://docs.travis-ci.com/user/languages/python/
#    - os: osx
#      osx_image: xcode8.2
#      python: 2.7
#  allow_failures:
#    - os: osx

before_install:
  - ./.travis/wget_miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - python -V
  - pip -V

# command to install dependencies
install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda install --yes --file requirements.txt
  - conda list
  - pip install -r futures_requirements.txt
  - pip install setuptools
  - pip list

# command to run tests
script: pytest