language: python

matrix:
  include:
    - os: linux
      dist: xenial
      python: 2.7
      sudo: required
    - os: linux
      dist: xenial
      python: 3.4
      sudo: required
    - os: linux
      dist: xenial
      python: 3.5
      sudo: required
    - os: linux
      dist: xenial
      python: 3.6
      sudo: required
    - os: osx
      osx_image: xcode8.2
      python: 3.5
      sudo: required
  allow_failures:
    - os: osx
    - python: 2.7

before_install:
  - ./.travis/wget_miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - python -V
  - pip -V

# command to install dependencies
install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda install --yes --file requirements.txt
  - conda list
  - pip install -r futures_requirements.txt
  - pip install setuptools
  - pip list

# command to run tests
script: pytest